version: '3.3'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    # We use the predefined Postgres image
    # image: mdillon/postgis:11-alpine
    # or copying and maaking their build
    build: ./services/db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=airQuality
      - POSTGRES_PASSWORD=airQuality
      - POSTGRES_DB=airQuality_dev
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres_data:
