version: '3.3'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
    expose:
      - 5000
      # ports expose to exterior, expose is only intern
      # since nginx will serve
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    # We use the predefined Postgres image
    # image: mdillon/postgis:11-alpine
    # or copying and maaking their build
    build: ./services/db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
